
//AMBIENTES
GET    http://localhost:3000/ambiente/all
Content-Type: application/json

###
GET    http://localhost:3000/token/all
Content-Type: application/json


//INVENTARIO
###
GET http://localhost:3000/inventario/all
Content-Type: application/json
###
GET http://localhost:3000/inventario/2
Content-Type: application/json
###
POST http://localhost:3000/inventario/create
Content-Type: application/json

{
    "id_inve":4,
    "fech_inve": "2020-02-02",
    "Obs_inve": "observacion 4",
    "Est_inve": "listo"
    
}

###
put http://localhost:3000/inventario/4/update
Content-Type: application/json

{   
    "fech_inve": "2023-02-02T00:00:00.000Z",
    "Obs_inve": "Observación 1",
    "Est_inve": "Dado de bajaja"
}



//USUARIO
###
GET http://localhost:3000/usuario/all
Content-Type: application/json

###
GET http://localhost:3000/usuario/178978
Content-Type: application/json

###
POST http://localhost:3000/usuario/create
Content-Type: application/json

{

    "num_doc":1234 ,
    "nom_fun":"juan",
    "num_doc":2 ,
    "nom_fun":"tati",

    "ape_fun":"manuel",
    "car_fun": "aprendiz",
    "correo_fun":"keiner@gmail.com",
    "rol_fun":"admin",
    "password":"12345678",
    "tip_doc":"cc ",
    "fot_use":"prueba",
    "est_email_func":"1",
    "tel_fun":"123",
    "id_rol_fk": 1
}

###
put http://localhost:3000/usuario/2/update
Content-Type: application/json

{
    "nom_fun":"tati",
    "ape_fun":"manuel",
    "car_fun": "aprendiz",
    "correo_fun":"jandy@gmail.com",
    "rol_fun":"admin",
    "password":"123",
    "tip_doc":"ti ",
    "fot_use":"prueba",
    "est_email_func":"1",
    "tel_fun":"123",
    "id_rol_fk": 1
}

//USUXINVE
###
GET http://localhost:3000/usuxinven/all
Content-Type: application/json
###
GET http://localhost:3000/usuxinven/321
Content-Type: application/json

###
POST http://localhost:3000/usuxinven/create
Content-Type: application/json

    {
        "id_fun": 1,
        "id_inve": 2
    }
    
###
PUT  http://localhost:3000/usuxinven/1/update
Content-Type: application/json

    {
        "id_inve": 2
    }
    




//MUNICIPIO
###
GET http://localhost:3000/municipio/all
Content-Type: application/json
###
GET http://localhost:3000/municipio/1
Content-Type: application/json
###
POST http://localhost:3000/municipio/create
Content-Type: application/json

{
    "id_muni": 2,
    "nom_muni":"prueba"
    
}

###
PUT  http://localhost:3000/municipio/2/update
Content-Type: application/json

{
    "nom_muni":"Antioquia"
}

//OBJETOS
###
GET http://localhost:3000/objeto/all
Content-Type: application/json
###
GET http://localhost:3000/objeto/1
Content-Type: application/json
###
POST http://localhost:3000/objeto/create
Content-Type: application/json

{
    "id_obj": 2,
    "id_cate":2,
    "ser_obj":"prueba",
    "id_amb": 1,
    "fech_adqui":"2024-04-12T10:03:23.000Z",
    "est_obj":"est_obj",
    "obser_obj":"prueba",
    "tip_obj":"prueba",
    "marc_obj":"prueba",
    "val_obj":123
}

###
put http://localhost:3000/objeto/1/update
Content-Type: application/json

  {
    "id_obj": 1,
    "id_cate": 1,
    "ser_obj": "12334",
    "id_amb": 1,
    "fech_adqui": "2024-03-11T15:00:45.000Z",
    "est_obj": "ACTIVO",
    "obser_obj": "MAL ESTADO",
    "tip_obj": "DEVOLUTIVO",
    "marc_obj": "ASUS",
    "val_obj": 11111
  }
  
//ROLES
###
GET http://localhost:3000/roles/all
Content-Type: application/json
###
GET http://localhost:3000/roles/1
Content-Type: application/json

###
POST http://localhost:3000/roles/create
Content-Type: application/json

{
    "id_Rol": 2,
    "nom_Rol":"admin",
    "createdAt": "2024-04-07 10:05:51",
    "updatedAt": "2024-04-16 10:05:53"
}

###
put http://localhost:3000/roles/1/update
Content-Type: application/json

{
    "id_Rol": 1,
    "nom_Rol": "PRUEBAS ",
    "createdAt": "2024-04-16T17:56:39.000Z",
    "updatedAt": "2024-04-09T17:56:41.000Z"
}

###
POST http://localhost:3000/users/createuser
Content-Type: application/json

{
    "username": "mariana",
    "password": "123",
    "apellido": "yepes",
    "telefono": "123456789"
}




###

PUT http://localhost:3000/users/editUser/6
Content-Type: application/json

{
    "username": "kevin",
    "password": "123",
    "apellido": "yepes",
    "telefono": "123456789"
}

###

DELETE  http://localhost:3000/users/deleteUser/2 
Content-Type: application/json


###

POST http://localhost:3000/users/allobj
Content-Type: application/json


###
POST http://localhost:3000/usuario/login
Content-Type: application/json

{
    "correo_fun":"jairo@gmail.com",
    "password":"123"
}
