GET    http://localhost:3000/centro/all
Content-Type: application/json

###

POST http://localhost:3000/users/createuser
Content-Type: application/json

{
    
    "username": "mariana",
    "password": "123",
    "apellido": "yepes",
    "telefono": "123456789"
}

###
POST http://localhost:3000/users/createFun
Content-Type: application/json
{
    "num_doc": 213,
    "nom_fun": "mariangel",
    "ape_fun": "ospino",
    "car_fun": "gerente",
    "correo_fun":"mari123@gmail.com", 
    "rol_fun": "administrador",
    "contra":  "123",
    "tip_doc": "Cc"
}
###

PUT http://localhost:3000/users/editUser/6
Content-Type: application/json

{
    "username": "kevin",
    "password": "123",
    "apellido": "yepes",
    "telefono": "123456789"
}

###

DELETE  http://localhost:3000/users/deleteUser/2 
Content-Type: application/json


###

POST http://localhost:3000/users/allobj
Content-Type: application/json
